- name: Config syslog
  connection: netconf
  hosts: "{{ host }}"
  gather_facts: false

  vars:    
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - name: Config syslog
    junos_logging:
     dest: host
     facility: any
     level: any
     name: "{{ server_ip }}"