- name: Get log
  connection: network_cli
  hosts: "{{ host }}"
  gather_facts: false
  tasks:
  - name: Get log
    junos_command:
     commands:  show log messages | last 200
    register: output

  - debug: msg="{{ output.stdout_lines }}"