- name: Config ip
  connection: netconf
  hosts: "{{ host }}"
  gather_facts: false 

  vars:    
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: get juniper facts
    junos_facts:
     gather_subset: all
    register: output
 
  - debug: msg="{{ output }}"