- name: Windows User management
  hosts: "{{ host }}"
  tasks:
  - name: Add new Windows User
    win_user:
      account_disabled: "{{ account_disabled }}"
      description: "{{ description }}"
      fullname: "{{ fullname }}"
      groups: "{{ groups }}"
      home_directory: "{{ home_directory }}"
      login_script: "{{ login_script }}"
      name: "{{ username }}"
      password: "{{ password }}"
      password_expired: "{{ password_expired }}"
      password_never_expires: "{{ password_never_expires }}"
      profile: "{{ profile }}"
      user_cannot_change_password: "{{ user_cannot_change_password }}"
      state: "present"