- name: Windows User management
  hosts: "{{ host }}"
  gather_facts: no
  tasks:
  - name: Add new Windows User
    win_user:
      account_disabled: "{{ account_disabled }}"
      description: "{{ description }}"
      fullname: "{{ fullname }}"
      groups: "{{ group }}"
      home_directory: "{{ home_directory }}"
      login_script: "{{ login_script }}"
      name: "{{ username }}"
      password: "{{ password }}"
      password_expired: "{{ password_expired }}"
      password_never_expires: "{{ password_never_expires }}"
      profile: "{{ profile }}"
      user_cannot_change_password: "{{ user_cannot_change_password }}"
      state: "present"

#Usage:ansible-playbook --extra-vars '{"host":["DESKTOP-AUKB810"],"account_disabled":"no","description":"this is a test acc","fullname":"tri le","group":["Users"],"home_directory":"","login_script":"","username":"trilx","password":"Anmbmkn123","password_expired":"no","password_never_expires":"yes","profile":"","user_cannot_change_password":"yes"}' ./yamls/windows_client/add_local_user.yml