- name: Windows User management
  hosts: "{{ host }}"
  tasks:
  - name: Add new Windows User
    win_user:
      account_disabled: "{{ account_disabled }}"
      description: "{{ description }}"
      fullname: "{{ fullname }}"
      groups: "{{ groups }}"    
      append: yes
      when: generate_ssh_key == "no"