- name: Windows User management
  hosts: "{{ host }}"
  gather_facts: no
  tasks:
  - name: Change user "{{ username }}" password
    ansible.windows.win_user:
      name: "{{ username }}"
      password: "{{ password }}"
      update_password: always
      state: present

#Usage: ansible-playbook --extra-vars '{"host":"DESKTOP-AUKB810","username":"wintltr","password":"Anmbmkn123"}' yamls/windows_client/change_user_password.yml