- name: Windows User management
  hosts: "{{ host }}"
  gather_facts: no
  tasks:

  - name: Create tmp directory before copying msi
    win_file:
      path: "{{ dest }}"
      state: directory

  - name: Copy File
    win_copy:
      src: "{{ source + '/' + filename }}"
      dest: "{{ dest }}\\{{ filename }}"
      remote_src: no

  - name: Install msi locally omitting the product_id
    win_package:
      path: "{{ dest }}\\{{ filename }}"
      state: present

  - name: Remove directory structure
    win_file:
      path: "{{ dest }}"
      state: absent

#Usage: ansible-playbook -e '{"host":"lth001-trilx","source":"/home/wintltr/Downloads/System-Monitoring-Web-App-master/msi","dest":"C:\\Users\\wintltr\\temtestestest123123","filename":"putty-64bit-0.76-installer.msi"}' yamls/windows_client/install_windows_program_local_msi.yml