- name: delete vlan
  connection: network_cli
  gather_facts: no
  hosts: "{{ host }}"
  tasks:
  - name: delete vlan
    ios_vlan:
     vlan_id: "{{ vlanId }}"
     state: absent

  - name: save running to startup when modified
    ios_config:
     save_when: modified
  