- name: Network module
  connection: network_cli
  gather_facts: no
  hosts: "{{ host }}"
  tasks:
  - name: Configure Static Route
    ios_static_route:
     prefix: "{{ prefix }}"
     mask: "{{ mask }}"
     next_hop: "{{ next_hop }}"

  - name: save running to startup when modified
    ios_config:
     save_when: modified