- name: Network module
  connection: network_cli
  gather_facts: no
  hosts: "{{ host }}"
  tasks:
  - name: Configure Static Route
    ios_static_route:
     prefix: "{{ prefix }}"
     mask: "{{ mask }}"
     next_hop: "{{ next_hop }}"