- name: Enable SNMPv3
  connection: local
  hosts: "{{ host }}"
  gather_facts: false
  become_method: enable
  tasks:
  - name: Enable SNMPv3
    ios_facts:
     gather_subset: all
     provider:
       authorize: yes
       auth_pass: "cisco"
    register: output

  - debug:
        msg: "{{ output.stdout_lines }}"
