- name: Network module
  connection: network_cli
  gather_facts: false
  hosts: "{{ host_var }}"
  tasks:
  - name: Get config for VyOS devices
    vyos_command:
     commands: show configuration
    register: output
      
  - debug: msg="{{ output.stdout_lines }}"