- name: Get Information Cisco
  connection: network_cli
  hosts: "{{ host }}"
  gather_facts: false
  tasks:
  - name: show log of vyos
    vyos_command:
      commands:
      - show log tail 200
    register: output
    
  - debug: msg="{{ output.stdout_lines }}"