- name: Install Package through link
  hosts: "{{ host_var }}"
  tasks:

  - name: Install package if OS is CentOS
    yum:
     name: "{{ link }}"
    when: ansible_facts['distribution'] == "CentOS"

  - name: Install package if OS is Ubuntu or Kali
    apt:
     deb: "{{ link }}"
    when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Kali GNU/Linux")


  
    
