- name: Run Test
  hosts: client1
  tasks:
  - name: Install the nginx rpm from a remote repo
    yum:
     name: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
     state: present  
     
