- name: Network module
  connection: network_cli
  gather_facts: false
  hosts: "{{ host_var }}"
  tasks:
  - name: Get config for VyOS devices
    vyos_facts:
     gather_network_resources: 
     - interfaces
     - l3_interfaces
      
  - debug: msg="{{ ansible_network_resources }}"
